name: Update Kodakku Scripts List

# 设置触发条件：当推送到 main 分支时自动运行
on:
  push:
    branches:
      - main
    paths:
      - 'Scripts/**' # 只有Scripts文件夹下的文件变动时才触发

jobs:
  build:
    runs-on: ubuntu-latest
    # 赋予工作流写入权限
    permissions:
      contents: write

    steps:
      # 步骤1：检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 拉取完整的历史记录，以便处理分支分叉的情况
          fetch-depth: 0

      # 步骤2：设置 .NET 环境
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # 确保版本与你的csproj文件匹配

      # 步骤3：运行C#解析器来生成JSON文件
      - name: Generate OnlineRepo.json
        run: dotnet run --project ScriptParser/ScriptParser.csproj

      # 步骤4：如果JSON文件有变动，则自动提交并推送
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update OnlineRepo.json list"
          file_pattern: OnlineRepo.json
          # 添加 git pull 命令来解决 non-fast-forward 错误
          push_options: --force
          skip_fetch: true
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
